notifications:
  webhooks:
    - https://webhook.commit-email.info/

language: cpp

compiler:
  - gcc
  - clang
env:
  - ENABLE_COVERAGE=no
  - ENABLE_COVERAGE=yes CONFIGURE_OPTIONS=--enable-coverage

apt_packages: &apt_packages
  packages:
    - autotools-dev
    - intltool
    - gtk-doc-tools
    - libgtk2.0-dev
    - libgoffice-0.8-dev
    - libgstreamer0.10-dev
    - libsoup2.4-dev

before_script:
  - ./autogen.sh
  - ./configure ${CONFIGURE_OPTIONS}

script:
  - test/run-test.sh

matrix:
  include:
    - name: "GCC"
      os: linux
      compiler: gcc
      addons:
        apt:
          <<: *apt_packages
    - name: "GCC with coverage"
      os: linux
      compiler: gcc
      addons:
        apt:
          <<: *apt_packages
        install:
          - sudo pip install cpp-coveralls
      env:
        CONFIGURE_OPTIONS: --enable-coverage
      after_success:
        - coveralls --exclude test
    - name: "Clang"
      os: linux
      compiler: clang
      addons:
        apt:
          <<: *apt_packages
    - name: "Clang with coverage"
      os: linux
      compiler: clang
      addons:
        apt:
          <<: *apt_packages
        install:
          - sudo pip install cpp-coveralls
      after_success:
        - coveralls --exclude test
    - name: "macOS"
      os: osx
      install:
        - brew bundle
