notifications:
  recipients:
    - kou@clear-code.com
install:
  - sudo apt-get install -y autotools-dev intltool gtk-doc-tools libgtk2.0-dev libgoffice-0.8-dev libgstreamer0.10-dev libsoup2.4-dev
before_script:
  - ./autogen.sh
  - ./configure
script:
  - test/run-test.sh
